import React, { Component } from 'react';
import { Row, Col, ListGroup, ListGroupItem } from 'react-bootstrap';
import './Resources.css';

// This is to get reducer
import { connect } from 'react-redux';

// This is to get from actionCreator
import { selectResource } from '../actions/resourcesActions';
// bindActionsCreator is to ensure that actions are generated by actionCreator and ends up
// throwing to all different reducers
import { bindActionCreators } from 'redux';

import ResourcesDetails from './ResourcesDetails';

class Resources extends Component {
    renderList = () => {
        return this.props.resourceLists.map((resourcesList) => {
            return (
                <ListGroupItem
                    key={resourcesList.title} 
                    bsStyle={resourcesList.style} 
                    header={resourcesList.header}

                    onClick={() => this.props.resourceSelected(resourcesList)}
                >
                    <u>{resourcesList.title}</u>
                </ListGroupItem>
            );
        });
    }
    render() {
        return (
                
            <div className="resources-row">
                <div className="resources-page-title">
                    <b>General Resources for Academic Improvement</b>
                </div>
                <div className="resources-page-subsection">
                    <b className="resources-subsection-title"><u>ESL Resources</u></b>
                    <p className="resources-subsection-description">Studying English (or any new language) requires <b>A LOT</b> of practice. To go from a
low beginner level to an advanced level typically takes 6 months to 1.5 years of
practicing everyday. And to be fluent, a language learner will need to practice
and immerse themselves in the target language for another 3 to 10 years! Most
native English speakers can understand and use more than 20,000 words. An
English language learner that wants to achieve an advanced or fluent level
should have a target of learning at least 8,000 to 10,000 words.</p>
                    <p className="resources-subsection-description">
                    You will need to not only know the meanings of these words but also use them
in the four skills of reading, writing, listening, and speaking. You will also need to
understand grammar, pronunciation, and even cultural norms to become
completely fluent. The following resources can provide some help in improving
these areas.
                    </p>
                </div>
                <hr/>
                <Row>
                    <Col xs={6} md={4} className="resources-options">
                        <ListGroup>
                            {this.renderList()}
                        </ListGroup>
                    </Col>

                    <Col xs={11} md={8} className="resources-description">
                        <ResourcesDetails />
                    </Col>
                </Row>
            </div>

        )
    }
}

// 1)
// Whatever is returned will show up as props inside of Resources(current component)
const mapStateToProps = (stateFromResources) => ({
    // Resources is referring to the rootReducer.js under the reducers folder
    resourceLists: stateFromResources.Resources
})

// 2)
// Below is for actionCreator under actions folder
const mapDispatchToProps = (dispatch) => (
    // Whenever selectResource is called, the result should be passed to all of our reducers(dispatch)
    bindActionCreators({ resourceSelected: selectResource }, dispatch )
)

// 1)
// export default connect(mapStateToProps)(Resources)

// 2)
export default connect(mapStateToProps, mapDispatchToProps)(Resources)